name: Noreg Bygg
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6923559
  brandStrength: 0.6290727
  lightness: 0.5294486
  brandColors:
    - '#FFFFFF'
    - '#5C667F'
    - '#88644C'
    - '#27150D'
    - '#C5C6D1'
  rhythmicContrast: 0.5
typography_spectrum: 0.3157895
layout_spectrum: 0.3258145
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
